# Generated by Django 5.2 on 2025-10-05 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_loginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_events', to='api.appuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_events_updated', to='api.appuser')),
            ],
            options={
                'db_table': 'catering_event',
            },
        ),
        migrations.CreateModel(
            name='CateringEventItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cateringevent')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_items', to='api.menuitem')),
            ],
            options={
                'db_table': 'catering_event_item',
            },
        ),
        migrations.AddIndex(
            model_name='cateringevent',
            index=models.Index(fields=['event_date', 'status'], name='catering_ev_event_d_2104e2_idx'),
        ),
        migrations.AddIndex(
            model_name='cateringevent',
            index=models.Index(fields=['client_name'], name='catering_ev_client__28fde0_idx'),
        ),
        migrations.AddIndex(
            model_name='cateringeventitem',
            index=models.Index(fields=['event'], name='catering_ev_event_i_4745c8_idx'),
        ),
    ]
