# Generated by Django 5.2 on 2025-10-13 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_menuitem_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_category',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='menu_catego_name_dba8c8_idx'), models.Index(fields=['sort_order'], name='menu_catego_sort_or_c6f489_idx')],
            },
        ),
    ]
