# Generated by Django 5.2.6 on 2025-10-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_cateringevent_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringevent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_events_deleted', to='api.appuser'),
        ),
    ]
