# Generated by Django 5.2 on 2025-10-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_cateringevent_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringevent',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to the order', max_digits=12),
        ),
    ]
