# Generated by Django 5.2.6 on 2025-10-18 11:42

import api.models
import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_facetemplate_deepface_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facetemplate',
            new_name='face_templa_model_n_a2ae7c_idx',
            old_name='face_templa_model_n_idx',
        ),
        migrations.AlterField(
            model_name='facetemplate',
            name='reference',
            field=models.FileField(blank=True, help_text='Reference face image for audit purposes', null=True, storage=api.storage.PrivateMediaStorage(), upload_to=api.models._facetpl_upload_path),
        ),
    ]
