# Generated by Django 5.2 on 2025-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_limit_employee_user_choices'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['role', 'status'], name='app_user_role_status_idx'),
        ),
    ]
