# Generated by Django 5.2.6 on 2025-10-20 13:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_appuser_app_user_role_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='credit_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loyalty credits available for purchases.', max_digits=12),
        ),
    ]
